/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_aduilio_nativemethods_MyJavaClass */

#ifndef _Included_com_example_aduilio_nativemethods_MyJavaClass
#define _Included_com_example_aduilio_nativemethods_MyJavaClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_aduilio_nativemethods_MyJavaClass
 * Method:    getInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_aduilio_nativemethods_MyJavaClass_getInfo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
